require('config.options').setup()
require('config.keymaps').setup()
require('config.autocmds').setup()

-- require('plugins.vague')
require('plugins.everforest')
require('plugins.conform')
require('plugins.mason')
require('plugins.luasnip')
require('plugins.nvim-cmp')
require('plugins.schemastore')
require('plugins.plenary')
require('plugins.mini-pairs')
require('plugins.nvim-surround')
require('plugins.nvim-highlight-colors')
require('plugins.gitsigns')
require('plugins.octo')
require('plugins.telescope')
require('plugins.vim-dadbod')

require('core.lsp')
